audit_header: false
title: New Orleans Real Estate Video Blog with Betsy Birdsong
description: Our mission at Birdsong Group is to be your best resource for New Orleans real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Birdsong Group, your professional New Orleans Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Betsy Birdsong
  title:
  license_number:
  about_markdown: |
    The Birdsong Group, Brokered by eXp Realty, is the leading full-service real estate brokerage in the Greater New Orleans area. Conveniently headquartered in Metairie, The Birdsong Group was founded as a dynamic boutique real estate group based on expert information, integrity, and innovation. Our Team, combined with the groundbreaking technological advancement and endless resources of eXp Realty, will give you an unparalleled real estate experience. We offer comprehensive real estate solutions for home buyers, investors, and house sellers provided by our Expert Advisors.
  brand: Birdsong Group
  brokerage: eXp Realty
  market: New Orleans
  address: 2201 Veterans Memorial Blvd Suite 405<br>Metairie, LA 70002
  phone: 504-780-9422
  phone_type:
  phone2:
  phone2_type:
  email: Team@TheBirdsongGroup.com
  url: https://www.thebirdsonggroup.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.findneworleansareahomes.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your New Orleans Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a New Orleans Home?"
    CTA_text2: "Search the entire MLS for your New Orleans home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.findneworleansareahomes.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: http://www.facebook.com/birdsongrealty
  linkedin_url: https://www.linkedin.com/company/the-birdsong-realty-group?trk=biz-companies-cym
  youtube_url:
  twitter_url: http://www.twitter.com/birdsongrealty
  instagram_url:
  pinterest_url: http://pinterest.com/birdsongrealty
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'New Orleans Real Estate Podcast with Betsy Birdsong'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the New Orleans Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Birdsong Group - your professional New Orleans Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in New Orleans, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Betsy Birdsong'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: New Orleans Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#0a2cb1'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
